# DO NOT EDIT! Automatically generated by scripts/generate_providers_and_account_vars.py
# To rebuild variables-accounts.tf, execute the generate_providers_and_account_vars GitHub workflow.


variable "account_Development" {
  type    = string
  default = "992382463129"
}

variable "account_Network" {
  type    = string
  default = "730335465148"
}

variable "account_management" {
  type    = string
  default = "730335412016"
}

variable "account_Production" {
  type    = string
  default = "590183937522"
}

variable "account_CommonServices" {
  type    = string
  default = "992382392462"
}

variable "account_Log_Archive" {
  type    = string
  default = "637423620536"
}

variable "account_Security" {
  type    = string
  default = "637423585692"
}

variable "account_Audit" {
  type    = string
  default = "058264173995"
}

variable "account_AFT" {
  type    = string
  default = "381491898007"
}

